### ISSUE TITLE
Error on Ctrax csv files saved in European Locale.

### ISSUE THREAD

**Issue by larroca** [Ax3man/trackr#23]
I have tried to read a large amount of Ctrax .csv files into tracker but I get an error message:

Error in names(x) <- do.call(paste0, as.list(new.names)) : 
  'names' attribute [6] must be the same length as the vector [1]

I can read multiple files using the same procedure with a small subset of these same files. Therefore, I assume that some of the .csv files that I provide must be incorrect, but currently is not possible to know which one is wrong without going back to the .csv files one by one. Is it possible to add that information to the error message?

Thanks!

**Comment by Ax3man** [comment]
Could you by any chance share some (any) collection of files that generate the error?

From the error it seems that you are trying to load 1 column .csv files. Either they really are one column (unlikely) or they are being read in wrongly. This could be due to Locale settings (i.e. using , or . as decimal separator), and can be due to saving those files in Excel.

**Comment by larroca** [comment]
Thanks! From your comment I have been able to manually find the file that was causing the error since I did manually edit (and not saved it properly) a .csv file obtained from Ctrax.

**Comment by Ax3man** [comment]
Ok, that's great. I'll plan to add a more informative error regardless.
